name: Update Contribution Chart

on:
  workflow_dispatch:

  schedule:
    - cron: "17 7 * * *"
      timezone: "Asia/Bangkok"

permissions:
  contents: write

jobs:
  update-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Generate contribution chart
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: Ohm5656
        run: python scripts/generate_contributions.py

      - name: Commit updated chart
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/yearly-contributions.svg

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "chore: update contribution chart"
          git push
